<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9</TargetFramework>
        <IsPackable>false</IsPackable>
        <RunSettingsFilePath>$(MSBuildProjectDirectory)\test.runsettings</RunSettingsFilePath>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MSTest" Version="4.0.2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\src\Jannesen.Library.Task.csproj" />
    </ItemGroup>

</Project>
